[package]
name = "cephes-stdtr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
single=[]

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0" }